
spring:
  application:
    name: apicard
  datasource:
    url: jdbc:mysql://localhost:3306/apicard?&createDatabaseIfNotExists=true
    username: root
    password: root
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

    open-in-view: false

  sql:
    init:
      mode: always
