
spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/apicard?&createDatabaseIfNotExists=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false #